// ===== Share Card Generator =====
App.share = {
  async generate() {
    const anime = await App.db.getAllAnime();
    const merch = (await App.db.getAllMerch()).filter(m => !m.isWishlist);
    const username = localStorage.getItem('av_user') || 'Anonymous';
    const totalCost = merch.reduce((s, m) => s + (m.price || 0), 0);
    const top5 = Object.entries(merch.reduce((acc, m) => { acc[m.animeName || ''] = (acc[m.animeName || ''] || 0) + (m.price || 0); return acc; }, {}))
      .sort((a, b) => b[1] - a[1]).slice(0, 5);
    const completed = anime.filter(a => a.status === 'completed').length;
    const watching = anime.filter(a => a.status === 'watching').length;

    const canvas = document.createElement('canvas');
    const dpr = 2;
    canvas.width = 600 * dpr; canvas.height = 800 * dpr;
    const ctx = canvas.getContext('2d');
    ctx.scale(dpr, dpr);
    const W = 600, H = 800;

    // Background
    ctx.fillStyle = '#15181e'; ctx.fillRect(0, 0, W, H);
    ctx.strokeStyle = 'rgba(255,255,255,0.045)';
    ctx.lineWidth = 1;
    for (let x = 0; x <= W; x += 40) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); }
    for (let y = 0; y <= H; y += 40) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke(); }

    // Title
    ctx.fillStyle = '#fff'; ctx.font = 'bold 32px Inter, sans-serif';
    ctx.fillText('AnimeVault', 40, 60);
    ctx.fillStyle = '#d5d7db'; ctx.font = '14px Inter, sans-serif';
    ctx.fillText(`@${username} 的收藏报告`, 40, 85);

    // Divider
    const grad = ctx.createLinearGradient(40, 100, 560, 100);
    grad.addColorStop(0, '#7b42bc'); grad.addColorStop(0.33, '#ffcf25'); grad.addColorStop(0.66, '#14c6cb'); grad.addColorStop(1, '#1868f2');
    ctx.fillStyle = grad; ctx.fillRect(40, 100, 520, 2);

    // Stats cards
    const stats = [
      { label: '收藏动漫', value: `${anime.length}`, color: '#7b42bc' },
      { label: '已看完', value: `${completed}`, color: '#14c6cb' },
      { label: '在追', value: `${watching}`, color: '#1868f2' },
      { label: '周边数', value: `${merch.length}`, color: '#ffcf25' },
    ];
    stats.forEach((s, i) => {
      const x = 40 + i * 133, y = 130;
      ctx.fillStyle = 'rgba(255,255,255,0.06)';
      ctx.beginPath(); ctx.roundRect(x, y, 120, 80, 8); ctx.fill();
      ctx.strokeStyle = 'rgba(178,182,189,0.24)'; ctx.stroke();
      ctx.fillStyle = s.color; ctx.font = 'bold 28px Inter'; ctx.textAlign = 'center';
      ctx.fillText(s.value, x + 60, y + 40);
      ctx.fillStyle = '#d5d7db'; ctx.font = '12px Inter';
      ctx.fillText(s.label, x + 60, y + 62);
    });
    ctx.textAlign = 'start';

    // Total cost
    ctx.fillStyle = '#ffcf25'; ctx.font = 'bold 20px Inter';
    ctx.fillText(`总花费: ${App.utils.formatCurrency(totalCost)}`, 40, 260);

    // Top 5 IP
    ctx.fillStyle = '#e2e8f0'; ctx.font = 'bold 16px Inter';
    ctx.fillText('最爱 IP TOP 5', 40, 310);

    top5.forEach(([name, cost], i) => {
      const y = 340 + i * 50;
      ctx.fillStyle = 'rgba(255,255,255,0.06)';
      ctx.beginPath(); ctx.roundRect(40, y, 520, 40, 8); ctx.fill();
      ctx.fillStyle = '#fff'; ctx.font = '14px Inter';
      ctx.fillText(`${i + 1}. ${name.length > 25 ? name.slice(0, 25) + '...' : name}`, 60, y + 26);
      ctx.fillStyle = '#14c6cb'; ctx.font = '13px Inter'; ctx.textAlign = 'end';
      ctx.fillText(App.utils.formatCurrency(cost), 540, y + 26);
      ctx.textAlign = 'start';
    });

    // Footer
    ctx.fillStyle = '#d5d7db'; ctx.font = '12px Inter';
    ctx.fillText(`Generated by AnimeVault · ${new Date().toLocaleDateString('zh-CN')}`, 40, H - 30);

    // Download
    const link = document.createElement('a');
    link.download = `animevault_${username}_${new Date().toISOString().slice(0,10)}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
    App.toast('分享卡片已生成！', 'success');
  }
};
